import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import { useForm } from "react-hook-form";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ResizablePanel from "@/components/ui/resizable-panel";
import { Textarea } from "@/components/ui/textarea";

type FormData = {
  url: string;
};

const Home: NextPage = () => {
  const [messages, setMessages] = useState([]);

  const { register, handleSubmit, setFocus } = useForm<FormData>({
    defaultValues: {
      url: "https://www.buildt.ai/blog/vm3qozd4qfrbbyzukqhynrwm9vb9tq",
    },
  });

  const onSubmit = async (formData: FormData) => {
    const res = await fetch("/api/bake-chat", {
      method: "POST",
      body: JSON.stringify({ url: formData.url }),
    });

    console.log("res", res);
  };

  return (
    <Layout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="mx-auto flex h-full w-full max-w-6xl flex-col items-center justify-center px-4 pb-2 pt-24 sm:max-w-lg">
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="mt-4 flex w-full max-w-lg items-center space-x-2"
        >
          <Input
            type="text"
            className="flex-1"
            placeholder="Type your url..."
            maxLength={100}
            {...register("url", {
              required: true,
              minLength: 1,
              maxLength: 100,
            })}
          />
          <Button>Start</Button>
        </form>

        <Textarea />

        <ResizablePanel>
          <AnimatePresence>
            <motion.div
              className="mt-4 flex h-full w-full flex-col items-center justify-center gap-y-4"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <div>Text</div>
            </motion.div>
          </AnimatePresence>
        </ResizablePanel>
      </section>
      <Footer />
    </Layout>
  );
};

export default Home;
