import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import { Send } from "lucide-react";
import { useForm } from "react-hook-form";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ResizablePanel from "@/components/ui/resizable-panel";
import { Textarea } from "@/components/ui/textarea";

type FormData = {
  url: string;
};

type FormData2 = {
  input: string;
};

const Home: NextPage = () => {
  const [messages, setMessages] = useState([]);

  const { register, handleSubmit, setFocus } = useForm<FormData>({
    defaultValues: {
      url: "https://www.buildt.ai/blog/vm3qozd4qfrbbyzukqhynrwm9vb9tq",
    },
  });

  const { register: register2, handleSubmit: handleSubmit2 } =
    useForm<FormData2>({
      defaultValues: {
        input: "",
      },
    });

  const onSubmit = async (formData: FormData) => {
    const res = await fetch("/api/prepare-chatbot", {
      method: "POST",
      body: JSON.stringify({ url: formData.url }),
    });

    console.log("res", res);
  };

  const onSubmit2 = async (formData: FormData2) => {
    const res = await fetch("/api/chat", {
      method: "POST",
      body: JSON.stringify({ input: formData.input }),
    });

    console.log("res", res);
  };

  return (
    <Layout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <section className="mx-auto flex h-screen flex-1 justify-between w-full max-w-6xl flex-col pb-2 pt-24 sm:max-w-lg">
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="mt-4 flex w-full max-w-lg items-center space-x-2"
        >
          <Input
            className="flex-1"
            placeholder="Type your url..."
            maxLength={100}
            {...register("url", {
              required: true,
              minLength: 1,
              maxLength: 100,
            })}
          />
          <Button>Start</Button>
        </form>
        <ResizablePanel>
          <AnimatePresence>
            <motion.div
              className="mt-4 flex h-full bg-slate-600 w-full flex-col items-center justify-center gap-y-4"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <Textarea />
            </motion.div>
          </AnimatePresence>
        </ResizablePanel>
        <div className="rounded-md px-2 py-2 mb-2 sm:mb-0">
          <div className="relative flex">
            {/* <input
              type="text"
              placeholder="Write your message!"
              className="w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-md py-3"
            /> */}
            <form onSubmit={handleSubmit2(onSubmit2)} className="w-full">
              <Input
                type="text"
                className="bg-slate-600 flex w-full outline-none border-none focus:outline-none focus:ring-0 focus:ring-offset-0"
                placeholder="Ask me anything!"
                maxLength={100}
                {...register2("input", {
                  required: true,
                  minLength: 1,
                  maxLength: 100,
                })}
              />
              <div className="absolute right-0 items-center inset-y-0 hidden sm:flex">
                <Button>
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </form>
          </div>
        </div>
      </section>
      {/* <Footer /> */}
    </Layout>
  );
};

export default Home;
